# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 23:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_counter', models.PositiveSmallIntegerField(default=0, verbose_name='Program counter (PC)')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default={}, verbose_name='Data of the program stack')),
                ('stack_pointer', models.PositiveSmallIntegerField(default=0)),
                ('stack_size', models.PositiveSmallIntegerField(default=0)),
                ('memory', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='program_stack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='computer.ProgramStack'),
        ),
    ]
