# -*- coding: utf-8 -*-


from __future__ import print_function, unicode_literals

from django.utils.crypto import get_random_string


class ComputerException(Exception):
    """
    Class that just to customize exceptions generated by `Computer` if needed.
    """
    pass


def generate_computer_id():
    """
    Just to make more friendly IDs.
    """
    return get_random_string(7).lower()
